# Generated by Django 4.0.5 on 2022-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=25)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('area', models.CharField(max_length=30)),
                ('pickup_address', models.TextField(max_length=40)),
                ('delivery_address', models.TextField(max_length=40)),
                ('package_dimension', models.CharField(max_length=25)),
                ('weight', models.CharField(max_length=10)),
                ('service', models.CharField(choices=[('EXPRESS', 'Express'), ('REGULAR', 'Regular'), ('INTERNATIONAL', 'International')], default='EXPRESS', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
            ],
        ),
    ]
